version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python demo.py
          name: Test
      - run:
          name: Code Has Arrived
          command: |
            ls ./ressources/
            echo '^^^That should look familiar^^^'
workflows:
  main:
    jobs:
      - build-and-test
